### ISSUE TITLE
Crash on rtp in sponge based private server

### ISSUE THREAD

**Issue by Bucky420** [ferreusveritas/Dynamic-Trees#102]
if u need more info ask atm i try to use the most updated forge and sponge for the server 

[05:46:33] [Server thread/INFO] [minecraft/DedicatedServer]: [Member] littleconnor1 :: why is /fly in the motd
[05:46:39] [Server thread/INFO] [jjcoin]: side server
[05:46:39] [Server thread/INFO] [jjcoin]: side server
[05:46:40] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3627ms behind, skip
ping 72 tick(s)
[05:46:41] [Server thread/INFO] [jjcoin]: side server
[05:46:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:862) ~[?:1.8.0_171]
        at java.util.Collections.max(Collections.java:708) ~[?:1.8.0_171]
        at com.ferreusveritas.dynamictrees.trees.TreeSpruce$SpeciesSpruce.postGeneration(TreeSpruce.java:102) ~[TreeSpruce$SpeciesSpruce.class:?]
        at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:186) ~[JoCode.class:?]
        at com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:947) ~[Species.class:?]
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:184) ~[TreeGenerator.class:?]
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.lambda$generate$0(TreeGenerator.java:100) ~[TreeGenerator.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_171]
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.generate(TreeGenerator.java:100) ~[TreeGenerator.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:571) ~[GameRegistry.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997) ~[axw.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbc000(PlayerChunkMapEntry.java:1079) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) ~[ou.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
[05:46:41] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/ntg/neo/./crash-reports/crash-2018-07-11_05.46.41-server.txt
[05:46:41] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[05:46:41] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[05:46:41] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[05:46:42] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
[05:46:42] [Server thread/INFO] [Sp

**Comment by codydbgt** [comment]
did u fix it?

**Comment by Bucky420** [comment]
thanks!

**Comment by ghost** [comment]
yes.  It's fixed in the current dev codebase.
