### ISSUE TITLE
crash ... ticking world

### ISSUE THREAD

**Issue by Bucky420** [ferreusveritas/Dynamic-Trees#107]
0.7.8
[crash-2018-07-22_06.33.46-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2216760/crash-2018-07-22_06.33.46-server.txt)

Description: Exception ticking world

java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at java.util.Collections.max(Collections.java:708)
	at com.ferreusveritas.dynamictrees.trees.TreeSpruce$SpeciesSpruce.postGeneration(TreeSpruce.java:102)
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:186)
	at com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:947)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:184)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.lambda$generate$0(TreeGenerator.java:100)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.generate(TreeGenerator.java:100)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:571)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbc000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at java.util.Collections.max(Collections.java:708)
	at com.ferreusveritas.dynamictrees.trees.TreeSpruce$SpeciesSpruce.postGeneration(TreeSpruce.java:102)
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:186)
	at com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:947)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:184)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.lambda$generate$0(TreeGenerator.java:100)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.generate(TreeGenerator.java:100)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:571)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbc000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

**Comment by ghost** [comment]
Didn't I already close this back in issue #102 ?

**Comment by Bucky420** [comment]
i guess not ? i forgot i posted that ... iv had some other issue with another mod that i know how to fix now but this has happened on the latest version of the mod. if there is any thing else i can do to help fix this let me know!

**Comment by ghost** [comment]
I haven't released the fix on curseforge yet.  You're still running the same version as the last time you submitted the bug.  Already fixed.
