### ISSUE TITLE
DynamicTrees-1.12.2-0.8.2.jar  Encountered an unexpected exception

### ISSUE THREAD

**Issue by jjamesk** [ferreusveritas/Dynamic-Trees#143]
Hello

I've just updated my small "minecraft server 1.12.2 forge-1.12.2-14.23.4.2758" with DynamicTrees-1.12.2-0.8.2.jar and the server will boot fine but when we connect to it the server errors with the following, i'll attach the crash and error log for more information, would appreciate any assistance.

[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/2474747/latest.log)
[crash-2018-10-13_00.20.28-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2474748/crash-2018-10-13_00.20.28-server.txt)

Caused by: java.lang.NoSuchMethodError: com.ferreusveritas.dynamictrees.blocks.BlockBranch.getRadius(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)I
	at rustic.compat.dynamictrees.DropCreatorFruit.getVoluntaryDrop(DropCreatorFruit.java:47) ~[DropCreatorFruit.class:?]
	at com.ferreusveritas.dynamictrees.systems.dropcreators.DropCreatorStorage.getVoluntaryDrop(DropCreatorStorage.java:79) ~[DropCreatorStorage.class:?]
	at com.ferreusveritas.dynamictrees.trees.Species.getVoluntaryDrops(Species.java:321) ~[Species.class:?]
	at com.ferreusveritas.dynamictrees.trees.Species.handleVoluntaryDrops(Species.java:371) ~[Species.class:?]
	at com.ferreusveritas.dynamictrees.trees.Species.update(Species.java:559) ~[Species.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.updateTree(BlockRooty.java:172) ~[BlockRooty.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.func_180645_a(BlockRooty.java:145) ~[BlockRooty.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more

**Comment by jjamesk** [comment]
It appears that an update to of rustic-1.0.12.jar was needed
