### ISSUE TITLE
[1.12.2] Registering blocks error

### ISSUE THREAD

**Issue by Masstrix** [ferreusveritas/Dynamic-Trees#19]
When generating a new world on a server the following error occurred.

`[13:14:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at com.ferreusveritas.dynamictrees.compat.CommonProxyCompat.registerBlocks(CommonProxyCompat.java:21) ~[CommonProxyCompat.class:?]
        at com.ferreusveritas.dynamictrees.ModBlocks.registerBlocks(ModBlocks.java:66) ~[ModBlocks.class:?]
        at com.ferreusveritas.dynamictrees.DynamicTrees$RegistrationHandler.registerBlocks(DynamicTrees.java:106) ~[DynamicTrees$RegistrationHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_109_RegistrationHandler_registerBlocks_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734) ~[GameData.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by ghost** [comment]
Caused by calling Minecraft.isFancyGraphicsEnabled() serverside.  This was caused by recently adding code to fix fast or fancy graphics for Dynamic Leaves blocks.
