### ISSUE TITLE
[0.7.2] Dedicated Server Crash, calling client-side method

### ISSUE THREAD

**Issue by An-Sar** [ferreusveritas/Dynamic-Trees#24]
It looks like 0.7.2 is calling a client side method in IBlockAccess, maybe getBiome()
Testing was done with forge-1.12.2-14.23.1.2582

`java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_180494_b(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/world/biome/Biome;
        at com.ferreusveritas.dynamictrees.trees.TreeOak$SpeciesSwampOak.isAcceptableSoilForWorldgen(TreeOak.java:89)
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:191)
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.generateOverworld(TreeGenerator.java:119)
        at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.generate(TreeGenerator.java:106)
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by ghost** [comment]
Why in hell is this function client side only? (Rhetorical question).  I'm going to change the IBlockAccess to World.

**Comment by ghost** [comment]
Also.. how did this get past weeks worth of alpha testing?  FFS.

**Comment by An-Sar** [comment]
yeah it seems a very strange method to be client only

**Comment by ghost** [comment]
I just submitted the new builds on curseforge for 0.7.2b.  It should work though I didn't test it thoroughly.
