### ISSUE TITLE
World Ticking Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [ferreusveritas/Dynamic-Trees#246]
Hello,

There seems to be an issue with World Gen and Galacticraft...and Dynamic Trees:

- https://paste.dimdev.org/mideqaqeze.mccrash

- https://mega.nz/#!w9chmQYQ!6H6EsWyaAxa1vicfkeomIqEEKVKEylvb1dpCTtb9vEg

- https://mega.nz/#!E0EVjKhS!jaYXwKwO140VQzMG91e_obgvcGIFhd7edhSY7a6Ecbs

I'm sending this message to both mods authors

Background: At first, I thought it was Optifine or Mo Creatures. I was wrong. Hopefully, you guys can help me figure out an answer

The two links after the crash log link, are the latest log that help me suspect there is an issue with Dynamic Trees, World Gen and Galacticraft.

The problem is mainly with a World Ticking Crash.

**Comment by kierajreed** [comment]
Please test this problem with fewer mods and a new world. Once you narrow down which mods cause the error it is a lot easier to help.

**Comment by RodrigoTaipe93** [comment]
[Mo Creatures - Latest Log.log](https://github.com/ferreusveritas/DynamicTrees/files/3115280/Mo.Creatures.-.Latest.Log.log)

I checked the log again...there seems to be an issue between World gen and a "falling tree" from Dynamic trees....
The issue is at the end of the log....
it says: 
- "Tried to add entity dynamictrees:falling_tree but it was marked as removed already"

**Comment by RodrigoTaipe93** [comment]
and that seems not to work well with Optifine...seems like Galacticraft just mentions the issue

**Comment by RodrigoTaipe93** [comment]
Hopes this helps:
[18:38:36] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:203]: java.lang.IllegalArgumentException: bound must be positive
[18:38:36] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:203]: 	at java.util.Random.nextInt(Unknown Source)
[18:38:36] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:203]: 	at com.ferreusveritas.dynamictrees.api.worldgen.BiomePropertySelectors$RandomSpeciesSelector.getSpecies(BiomePropertySelectors.java:117)
