### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GreyMamoN** [ferreusveritas/Dynamic-Trees#26]
Forge Mod Loader version 14.23.1.2575
DynamicTrees-1.12.2-0.7.2b

[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_180494_b(Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/world/biome/Biome;
	at com.ferreusveritas.dynamictrees.trees.TreeOak.getSpeciesForLocation(TreeOak.java:197) ~[TreeOak.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRootyDirt.getSpecies(BlockRootyDirt.java:311) ~[BlockRootyDirt.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRootyDirt.updateTree(BlockRootyDirt.java:148) ~[BlockRootyDirt.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRootyDirt.func_180645_a(BlockRootyDirt.java:132) ~[BlockRootyDirt.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more

**Comment by ghost** [comment]
Confounded all stupid IBlockAccess getBiome should not be Client Side Only.  Changed to World.

**Comment by ghost** [comment]
I just uploaded version 0.7.2c which has the fix.  Should take care of the problem. Let me know.
