### ISSUE TITLE
[1.12.2] Crash in Creative (Minor Bug)

### ISSUE THREAD

**Issue by Cakx** [ferreusveritas/Dynamic-Trees#37]
Hey there! Awesome mod so far.

I found a bug in creative mode.
Placing a dynamic leaf that was cloned from a tree using the middle mouse button crashes the game.
Using the middle mouse button on your dynamic leafes should probably give you a vanilla leaf or a dynamic leaf with valid meta data. :)
Luckily this bug is no concern for survial mode but fixing it would be conveniant. 

Log:

[18:50:08] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.getStateForPlacement(BlockDynamicLeaves.java:156) ~[BlockDynamicLeaves.class:?]
at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:52) ~[ahb.class:?]
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:860) ~[ForgeHooks.class:?]
at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more
Das Program ist mit dem Status -805306369 abgestürzt.

**Comment by ghost** [comment]
Thanks for reporting. Fixed in the dev version.
