### ISSUE TITLE
Crash on Dynamic.Trees-v0.9.7

### ISSUE THREAD

**Issue by Maks-Haswell** [ferreusveritas/Dynamic-Trees#417]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2020-04-08 23:31:25 VLAT
Description: Rendering entity in world

java.lang.NullPointerException
    at com.ferreusveritas.dynamictrees.models.ModelEntityFallingTree.generateTreeQuads(ModelEntityFallingTree.java:75)
    at com.ferreusveritas.dynamictrees.models.ModelEntityFallingTree.<init>(ModelEntityFallingTree.java:41)
    at com.ferreusveritas.dynamictrees.models.ModelTrackerCacheEntityFallingTree.lambda$getModel$0(ModelTrackerCacheEntityFallingTree.java:19)
    at java.util.HashMap.computeIfAbsent(Unknown Source)
    at com.ferreusveritas.dynamictrees.models.ModelTrackerCacheEntityFallingTree.getModel(ModelTrackerCacheEntityFallingTree.java:19)
    at com.ferreusveritas.dynamictrees.render.RenderFallingTree.doRender(RenderFallingTree.java:52)
    at com.ferreusveritas.dynamictrees.render.RenderFallingTree.doRender(RenderFallingTree.java:30)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392)
    at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zch000(RenderGlobal.java:3753)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:849)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1801)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:330)
    at launcher.lOlkEKchebureK.main(SourceFile:210)

**Comment by kil0byt3** [comment]
Same issue: https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/128

**Comment by democat3457** [comment]
bump

**Comment by kierajreed** [comment]
Mod list, please; and a description of how the error occurred. There's very little helpful info here.

**Comment by kierajreed** [comment]
Also, please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by Stephano95** [comment]
I found Dynamic trees crashed as well. Have attached crash report.
[crash-2020-05-18_18.06.02-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/4642295/crash-2020-05-18_18.06.02-client.txt)

**Comment by Stephano95** [comment]
Downloaded it a second time and it worked that time.

**Comment by ghost** [comment]
Added a null check that should fix the problem if whatever conditions re-emerge.

**Comment by ghost** [comment]
Latest curseforge download should resolve this issue.
