### ISSUE TITLE
ticking entity error dynamictrees:falling_tree 

### ISSUE THREAD

**Issue by grisha252** [ferreusveritas/Dynamic-Trees#520]
I keep getting this error when I try to log in.  Do you have any ideas how to fix?

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2021-05-04 16:30:13 PDT
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 0
    at com.ferreusveritas.dynamictrees.util.BranchDestructionData.getBranchBlockState(BranchDestructionData.java:188)
    at com.ferreusveritas.dynamictrees.entities.animation.AnimationHandlerPhysics.handleMotion(AnimationHandlerPhysics.java:85)
    at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.handleMotion(EntityFallingTree.java:352)
    at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.onEntityUpdate(EntityFallingTree.java:276)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:389)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zdk000$updateEntity(World.java:5623)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: dynamictrees:falling_tree (com.ferreusveritas.dynamictrees.entities.EntityFallingTree)
  Entity ID: 18827
  Entity Name: entity.falling_tree.name
  Entity's Exact location: -590.50, 79.17, 10.50
  Entity's Block location: World: (-591,79,10), Chunk: (at 1,4,10 in -37,0; contains blocks -592,0,0 to -577,255,15), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
  Entity's Momentum: 0.00, 0.17, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.16660000389963392d,0.0d],UUIDLeast:-7676706981047308049L,RelativeAABB:[-6.5d,-4.166600003899632d,-7.5d,7.5d,5.833399996100368d,8.5d],Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[0.95230454f,0.51821727f],UpdateBlocked:0b,FallDistance:0.0f,UUIDMost:-3253263929019185136L,Pos:[-590.5d,79.16660000389963d,10.5d],Fire:0s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}},SurgeAABB:[-597.0d,75.0d,3.0d,-583.0d,85.0d,19.0d],vox:{geomz:0.0d,geomy:0.25d,geomx:0.0d,massy:0.14285714285714285d,massx:0.0d,trunkheight:2,massz:0.0d,branchcon:[I;33826,33619968,33589280,33587202],volume:0.109375f,destroytype:3,onfire:1b,leaves:[I;54607934,21119551,21119552,21053501,54607936,21119553,21054018,20987965,21119040,71385153,71319618,21119041,54607938,20987971,21119042,21053507,21053246,21119295,21119808,21119294,71385408,37830974,21119296,54608193,54542658,20922691,21053757,21119297,37830978,20988227,20988221,21119298,21053763,21053250,20922685,21119039,21119038,71385151],species:"rustic:olive",cutz:10,ends:[I;4211008,4210751,4210753],cutx:-591,cuty:79,branchpos:[I;37765184,20987967,20987969,20988224],cutdir:0,tooldir:0}}

**Comment by grisha252** [comment]
I forgot to add that I am on 1.12.2  and using the latest version of dynamic trees.

**Comment by Harleyoc1** [comment]
Fixed in 252d611e163c80c5a47d36966115fa70241d6d78. Will come in the next patch. Until then you could use 0.9.22 since I believe this was caused by recent changes to the tree falling animation.

**Comment by grisha252** [comment]
Thank for the quick reply. 

My kids and I LOVE this mod!

Great work. 

Gary
