### ISSUE TITLE
Crash when got  out of a generated structure

### ISSUE THREAD

**Issue by aburone** [ferreusveritas/Dynamic-Trees#546]
DynamicTrees-1.16.5-0.10.0-Beta12.jar
DynamicTreesForbiddenArcanus-1.16.5-1.1.1.jar
DynamicTreesNaturesAura-1.16.5-1.2.2.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar

**Describe the bug**
I've spend some time inside a generated structure. Upon exit I got this crash. And now the game crashes every time I try to load the world (same error). Had to remove the mods :/

[20May2021 13:30:40.073] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=coredir, clazz=class com.ferreusveritas.dynamictrees.util.CoordUtils$Surround, values=[N, NW, W, SW, S, SE, E, NE]} as it does not exist in Block{minecraft:grass_block}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseDir(TrunkShellBlock.java:127) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseUnchecked(TrunkShellBlock.java:142) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseUnchecked(TrunkShellBlock.java:137) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuse(TrunkShellBlock.java:168) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuse(TrunkShellBlock.java:163) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.func_196253_a(TrunkShellBlock.java:123) ~[dynamictrees:1.16.5-0.10.0-Beta12]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196953_a(AbstractBlock.java:665) ~[?:?]
	at xreliquary.items.LanternOfParanoiaItem.isBadPlacementToTry(LanternOfParanoiaItem.java:94) ~[xreliquary:1.16.5-1.3.5.1098]
	at xreliquary.items.LanternOfParanoiaItem.tryToPlaceAtPos(LanternOfParanoiaItem.java:84) ~[xreliquary:1.16.5-1.3.5.1098]
	at xreliquary.items.LanternOfParanoiaItem.lambda$inventoryTick$0(LanternOfParanoiaItem.java:63) ~[xreliquary:1.16.5-1.3.5.1098]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) ~[?:?]
	at xreliquary.items.LanternOfParanoiaItem.func_77663_a(LanternOfParanoiaItem.java:63) ~[xreliquary:1.16.5-1.3.5.1098]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434) ~[?:?]
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]

**Comment by LuminousPath** [comment]
Similar error with building gadgets trying to access the same Abstract Block interface:

```
java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=coredir, clazz=class com.ferreusveritas.dynamictrees.util.CoordUtils$Surround, values=[N, NW, W, SW, S, SE, E, NE]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseDir(TrunkShellBlock.java:127) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseUnchecked(TrunkShellBlock.java:142) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuseUnchecked(TrunkShellBlock.java:137) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuse(TrunkShellBlock.java:168) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.getMuse(TrunkShellBlock.java:163) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.branches.TrunkShellBlock.func_196253_a(TrunkShellBlock.java:123) ~[dynamictrees:1.16.5-0.10.0-Beta10] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196953_a(AbstractBlock.java:665) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:notreepunching.mixins.json:block.AbstractBlockStateAccess,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:APP:betterfoliage.common.mixins.json:MixinBlockState,pl:mixin:A}
	at com.direwolf20.buildinggadgets.common.items.modes.AbstractMode.validator(AbstractMode.java:62) ~[buildinggadgets:3.8.0] {re:classloading}
	at com.direwolf20.buildinggadgets.common.items.modes.AbstractMode.lambda$getCollection$0(AbstractMode.java:50) ~[buildinggadgets:3.8.0] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_292] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292] {}
	at com.direwolf20.buildinggadgets.common.items.modes.AbstractMode.getCollection(AbstractMode.java:52) ~[buildinggadgets:3.8.0] {re:classloading}
	at com.direwolf20.buildinggadgets.client.renders.BuildRender.lambda$render$0(BuildRender.java:72) ~[buildinggadgets:3.8.0] {re:classloading}
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_292] {}
	at com.direwolf20.buildinggadgets.client.renders.BuildRender.render(BuildRender.java:70) ~[buildinggadgets:3.8.0] {re:classloading}
	at com.direwolf20.buildinggadgets.client.events.EventRenderWorldLast.renderWorldLastEvent(EventRenderWorldLast.java:26) ~[buildinggadgets:3.8.0] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_564_EventRenderWorldLast_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:610) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:seamless_loading_screen.mixins.json:GameRendererMixin,pl:mixin:APP:fruittrees.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:seamless_loading_screen.mixins.json:GameRendererMixin,pl:mixin:APP:fruittrees.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```

**Comment by LuminousPath** [comment]
After looking at this a bit more, seems like in my case it's more building gadgets' problem.

For the original poster: more than likely xreliquary is doing something similar, so you might need to take this up with them.

**Comment by Harleyoc1** [comment]
> After looking at this a bit more, seems like in my case it's more building gadgets' problem.
> 
> For the original poster: more than likely xreliquary is doing something similar, so you might need to take this up with them.

From inspecting the crash seems to be exactly the problem. The call is sending the wrong block state. @aburone please report this to xreliquary instead.
