### ISSUE TITLE
DT Quark crash on boot. Missing biome type?

### ISSUE THREAD

**Issue by kirknay** [ferreusveritas/Dynamic-Trees#550]
DT Quark is causing a crash on loading, before title screen. Crash log to follow. According to the log there seems to be a missing biome tag, for whatever reason.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/26/21 8:53 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9467/870713306.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8252/798113115.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/1910034407.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at maxhyper.dtquark.DynamicTreesQuark.commonSetup(DynamicTreesQuark.java:31) ~[?:1.16.5-2.0.3] {re:classloading}
-- MOD dtquark --
Details:
	Mod File: DynamicTreesQuark-1.16.5-2.0.3.jar
	Failure message: Dynamic Trees for Quark (dtquark) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: vazkii.quark.base.world.config.BiomeTypeConfig.<init>(Z[Lnet/minecraft/world/biome/Biome$Category;)V
	Mod Version: 1.16.5-2.0.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: vazkii.quark.base.world.config.BiomeTypeConfig.<init>(Z[Lnet/minecraft/world/biome/Biome$Category;)V
Stacktrace:
	at maxhyper.dtquark.DynamicTreesQuark.commonSetup(DynamicTreesQuark.java:31) ~[?:1.16.5-2.0.3] {re:classloading}
	at maxhyper.dtquark.DynamicTreesQuark$$Lambda$6078/1811890293.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2910/46767245.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2539/1441398874.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3180/280395604.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3554897600 bytes (3390 MB) / 5011144704 bytes (4779 MB) up to 10498867200 bytes (10012 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx11264m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		create-stuff-additions1.16.5_v1.0.3.jar           |Create Stuff Additions        |create_stuff_additions        |1.0.2               |SIDED_SETU|NOSIGNATURE
		jei-1.16.5-7.7.0.100.jar                          |Just Enough Items             |jei                           |7.7.0.100           |SIDED_SETU|NOSIGNATURE
		autooredictconv-1.16.4-16.1.10.jar                |Auto Ore Dictionary Converter |autooredictconv               |16.1.10             |SIDED_SETU|NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|SIDED_SETU|NOSIGNATURE
		TerraForged-1.16.5-0.2.10.jar                     |TerraForged                   |terraforged                   |0.2.10              |SIDED_SETU|7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		mgui-1.16.5-3.2.0.jar                             |mgui                          |mgui                          |3.2.0               |SIDED_SETU|NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.1.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.1               |SIDED_SETU|NOSIGNATURE
		Controlling-7.0.0.19.jar                          |Controlling                   |controlling                   |7.0.0.19            |SIDED_SETU|NOSIGNATURE
		ColtCosmeticArmorMod-1.2.5.jar                    |Colt's Cosmetic Armour Mod    |ccam                          |1.0.1               |SIDED_SETU|NOSIGNATURE
		mdecore-1.16.4-16.1.0.jar                         |MattDahEpic Core              |mdecore                       |16.1.0              |SIDED_SETU|NOSIGNATURE
		Bookshelf-1.16.5-10.0.8.jar                       |Bookshelf                     |bookshelf                     |10.0.8              |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BedBenefits-1.16.5-5.0.3.jar                      |BedBenefits                   |bedbenefits                   |5.0.3               |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.7.jar                             |Tips                          |tips                          |4.0.7               |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		environmentalcreepers-forge-1.16.3-1.6.0.jar      |Environmental Creepers        |environmentalcreepers         |1.6.0               |SIDED_SETU|NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |SIDED_SETU|NOSIGNATURE
		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		iChunUtil-1.16.5-10.4.0.jar                       |iChunUtil                     |ichunutil                     |10.4.0              |SIDED_SETU|NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |SIDED_SETU|8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		JustEnoughResources-1.16.5-0.12.1.114.jar         |Just Enough Resources         |jeresources                   |0.12.1.114          |SIDED_SETU|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |SIDED_SETU|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |SIDED_SETU|NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		torchmaster-2.3.7.jar                             |Torchmaster                   |torchmaster                   |2.3.7               |SIDED_SETU|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |SIDED_SETU|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |SIDED_SETU|NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.0-135.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.0-135    |SIDED_SETU|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		baubles-1.8.7-1.16.5.jar                          |Baubles                       |baubles                       |1.8.7               |SIDED_SETU|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |SIDED_SETU|NOSIGNATURE
		tetra-1.16.5-3.11.1.jar                           |Tetra                         |tetra                         |3.11.1              |SIDED_SETU|NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |SIDED_SETU|NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |SIDED_SETU|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |SIDED_SETU|NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.3.0.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.3.0               |SIDED_SETU|NOSIGNATURE
		ftb-ultimine-1605.2.0-build.26-forge.jar          |FTB Ultimine                  |ftbultimine                   |1605.2.0-build.26   |SIDED_SETU|NOSIGNATURE
		tombstone-1.16-6.3.8.jar                          |Corail Tombstone              |tombstone                     |6.3.8               |SIDED_SETU|NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |SIDED_SETU|NOSIGNATURE
		structurize-0.13.174-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.174-ALPHA      |SIDED_SETU|NOSIGNATURE
		buildersaddition-1.16.5-20210517a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210517a    |SIDED_SETU|NOSIGNATURE
		minecolonies-0.14.182-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.14.182-ALPHA      |SIDED_SETU|NOSIGNATURE
		architectury-1.16.15-forge.jar                    |Architectury                  |architectury                  |1.16.15             |SIDED_SETU|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |SIDED_SETU|NOSIGNATURE
		BackTools-1.16.5-10.1.0.jar                       |Back Tools                    |backtools                     |10.1.0              |SIDED_SETU|NOSIGNATURE
		light-overlay-5.8.1.jar                           |Light Overlay                 |lightoverlay                  |5.8.1               |SIDED_SETU|NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |SIDED_SETU|NOSIGNATURE
		Aquaculture-1.16.5-2.1.19.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.19       |SIDED_SETU|NOSIGNATURE
		CraftableHorseArmour-1.16.X-1.4.0.jar             |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.16.4-1.4.0        |SIDED_SETU|NOSIGNATURE
		AncientGuns_3.2_1.16.4.jar                        |Ancient Guns                  |ancient_guns                  |3.2                 |SIDED_SETU|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |SIDED_SETU|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v2.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v2           |SIDED_SETU|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		DynamicTrees-1.16.5-0.10.0-Beta12.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta12|SIDED_SETU|NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta8  |SIDED_SETU|NOSIGNATURE
		DynamicTreesQuark-1.16.5-2.0.3.jar                |Dynamic Trees for Quark       |dtquark                       |1.16.5-2.0.3        |ERROR     |NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |SIDED_SETU|NOSIGNATURE
		createaddition-1.16.5-20210517a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20210517a    |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: a66daaaf-b1f9-437d-9629-7870bd95d87d
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Harleyoc1** [comment]
This is **not** the place for crashes with addons. Please report this [here](https://github.com/supermassimo/DynamicTrees-ExC/issues) instead (and use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com) for crash reports or logs).
