### ISSUE TITLE
Beta21 crashes with BOP DT on 1.16.5 forge 36.1.31

### ISSUE THREAD

**Issue by Mr-Syntax** [ferreusveritas/Dynamic-Trees#600]
sorry bro i know you tried to fix it but now i cant get the pack to boot with BOP DT

couldent really find a proper log but hopefully its this one, ill post it on his aswell, thanks for trying to fix it so fast  :)

[18:19:58] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.0.jar:9.0]
	at jdk.nashorn.internal.scripts.Script$Recompilation$54$5956A$\^eval\_.initializeCoreMod$transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.NashornFactory$$Lambda$430/698062929.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$456/1990419108.buildTransformedClassNodeFor(Unknown Source) [modlauncher-8.0.9.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:214) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:202) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.31.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/567921924.call(Unknown Source) [forge-1.16.5-36.1.31.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[18:19:59] [main/INFO]: start
[18:19:59] [main/INFO]: find block call
[18:19:59] [main/INFO]: Found return
[18:20:00] [main/WARN]: Error loading class: io/github/apace100/origins/origin/OriginManager (java.lang.ClassNotFoundException: null)
[18:20:00] [main/WARN]: @Mixin target io.github.apace100.origins.origin.OriginManager was not found survive.mixins.json:OriginManagerMixin
[18:20:00] [main/WARN]: @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in imm_ptl_mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[18:20:00] [main/INFO]: start
[18:20:00] [main/INFO]: find block call
[18:20:01] [main/WARN]: @Mixin target net/minecraft/client/renderer/WorldRenderer$LocalRenderInformationContainer is public in imm_ptl_mixins.json:client.render.MixinWorldRendererChunkInfo and should be specified in value
[18:20:01] [main/WARN]: @Mixin target net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$ChunkRender$ChunkRenderTask is public in imm_ptl_mixins_forge.json:client.MixinChunkRenderTask and should be specified in value
[18:20:01] [main/WARN]: @Mixin target net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$ChunkRender$RebuildTask is public in imm_ptl_mixins_forge.json:client.MixinRebuildTask and should be specified in value
[18:20:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[18:20:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[18:20:01] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[18:20:03] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.0.jar:9.0]
	at jdk.nashorn.internal.scripts.Script$Recompilation$54$5956A$\^eval\_.initializeCoreMod$transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.NashornFactory$$Lambda$430/698062929.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:290) [?:?]
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101) [?:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) [?:?]
	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:122) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.31.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/567921924.call(Unknown Source) [forge-1.16.5-36.1.31.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[18:20:04] [main/INFO]: start
[18:20:04] [main/INFO]: find block call
[18:20:04] [main/WARN]: @Redirect conflict. Skipping cavesandcliffs.glowsquid.mixins.json:client.renderer.SignTileEntityRendererMixin->@Redirect::renderGlow(Lnet/minecraft/client/gui/FontRenderer;Lnet/minecraft/util/IReorderingProcessor;FFIZLnet/minecraft/util/math/vector/Matrix4f;Lnet/minecraft/client/renderer/IRenderTypeBuffer;ZII)I with priority 1000, already redirected by upgrade_aquatic.mixins.json:SignTileEntityRendererMixin->@Redirect::redirectFont(Lnet/minecraft/client/gui/FontRenderer;Lnet/minecraft/util/IReorderingProcessor;FFIZLnet/minecraft/util/math/vector/Matrix4f;Lnet/minecraft/client/renderer/IRenderTypeBuffer;ZII)I with priority 1000
[18:20:06] [pool-3-thread-1/INFO]: Using Java 8 class definer
[18:20:06] [pool-3-thread-1/WARN]: Method overwrite conflict for setGlowing in cavesandcliffs.glowsquid.mixins.json:common.tileentity.SignTileEntityMixin, previously written by com.minecraftabnormals.upgrade_aquatic.core.mixin.SignTileEntityMixin. Skipping method.
[18:20:06] [pool-3-thread-1/WARN]: Method overwrite conflict for isGlowing in cavesandcliffs.glowsquid.mixins.json:common.tileentity.SignTileEntityMixin, previously written by com.minecraftabnormals.upgrade_aquatic.core.mixin.SignTileEntityMixin. Skipping method.
[18:20:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:20:12] [Render thread/INFO]: Setting user: LvL_85_tank
[18:20:12] [Render thread/ERROR]: java.io.FileNotFoundException: Source 'C:\Users\Chosen\Twitch\Minecraft\Instances\Debug6\config\defaultoptions\servers.dat' does not exist
[18:20:12] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraft.launchwrapper.Launch
[18:20:12] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:20:13] [Render thread/INFO]: [OptiFine] 
[18:20:13] [Render thread/INFO]: [OptiFine] OptiFine_1.16.5_HD_U_G7
[18:20:13] [Render thread/INFO]: [OptiFine] Build: 20210305-003221
[18:20:13] [Render thread/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[18:20:13] [Render thread/INFO]: [OptiFine] Java: 1.8.0_51, Oracle Corporation
[18:20:13] [Render thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[18:20:13] [Render thread/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[18:20:13] [Render thread/INFO]: [OptiFine] OpenGL: NVIDIA GeForce GTX 1080/PCIe/SSE2, version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
[18:20:13] [Render thread/INFO]: [OptiFine] OpenGL Version: 4.6.0
[18:20:13] [Render thread/INFO]: [OptiFine] Maximum texture size: 32768x32768
[18:20:13] [VersionCheck/INFO]: [OptiFine] Checking for new version
[18:20:13] [Render thread/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 471.11
[18:20:13] [Render thread/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[18:20:13] [Render thread/INFO]: [Shaders] Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
[18:20:13] [Render thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[18:20:13] [Render thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[18:20:13] [Render thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[18:20:13] [Render thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[18:20:13] [Render thread/INFO]: [Shaders] Load shaders configuration.
[18:20:13] [Render thread/INFO]: [Shaders] Loaded shaderpack: (internal)
[18:20:13] [VersionCheck/INFO]: [OptiFine] Version found: G7
[18:20:13] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[18:20:13] [Render thread/INFO]: [OptiFine] Using legacy block aliases: flattening_ids.txt
[18:20:13] [Render thread/INFO]: [OptiFine] Legacy block aliases: 2751
[18:20:13] [Render thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.itemConsumer
[18:20:13] [Render thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.tessellator
[18:20:13] [Render thread/INFO]: start cleaning shader context []
[18:20:13] [Render thread/INFO]: shader context template updated
[18:20:15] [Render thread/INFO]: Potentially Dangerous alternative prefix `citadel` for name `debug`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[18:20:15] [Render thread/INFO]: Potentially Dangerous alternative prefix `citadel` for name `citadel_book`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[18:20:15] [Render thread/INFO]: Potentially Dangerous alternative prefix `walljump` for name `walljump`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[18:20:15] [Render thread/INFO]: Potentially Dangerous alternative prefix `walljump` for name `doublejump`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[18:20:15] [Render thread/INFO]: Potentially Dangerous alternative prefix `walljump` for name `speedboost`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[18:20:16] [modloading-worker-1/INFO]: Infernal Expansion: Blocks Registered!
[18:20:16] [modloading-worker-2/INFO]: [com.mactso.harderspawners.Main:<init>:26]: harderspawners: Registering Mod.
[18:20:16] [modloading-worker-1/INFO]: Infernal Expansion: Items Registered!
[18:20:16] [modloading-worker-1/INFO]: Infernal Expansion: Entity Types Registered!
[18:20:16] [modloading-worker-1/INFO]: Infernal Expansion: Painting Types Registered!
[18:20:16] [modloading-worker-1/INFO]: Infernal Expansion: Tile Entity Types Registered!
[18:20:18] [modloading-worker-2/INFO]: Found return
[18:20:18] [modloading-worker-1/INFO]: Carrots Lib mod constructor called
[18:20:18] [modloading-worker-1/INFO]: Potion effect neutralizer hook initialized successfully!
[18:20:18] [modloading-worker-1/INFO]: Potion type converter hook initialized successfully!
[18:20:18] [modloading-worker-1/INFO]: Setting *DEFAULT* builtin as default season provider
[18:20:18] [modloading-worker-1/INFO]: Using configured thresholds as Day-Night state provider
[18:20:18] [modloading-worker-1/INFO]: Registered Curios mod as primary baubles provider
[18:20:19] [modloading-worker-3/WARN]: @Final field field_187234_c:Ljava/util/Map; in performant.mixins.json:entity.EntityDataManagerMixin should be final
[18:20:20] [modloading-worker-5/ERROR]: Failed to register automatic subscribers. ModID: dtbop, class therealeststu.dtbop.DynamicTreesBOP
java.lang.NoClassDefFoundError: com/ferreusveritas/dynamictrees/api/treedata/IDropCreator
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3572/2058895059.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) [?:36.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3167/2103548875.run(Unknown Source) [?:36.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3519/259915853.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: com.ferreusveritas.dynamictrees.api.treedata.IDropCreator
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 16 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
		at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?]
		at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3572/2058895059.accept(Unknown Source) ~[?:?]
		at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) [?:36.1]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3167/2103548875.run(Unknown Source) [?:36.1]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) [?:?]
		at net.minecraftforge.fml.ModContainer$$Lambda$3519/259915853.run(Unknown Source) [?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by Harleyoc1** [comment]
You need to update DT BOP, that error would have been fixed already. Anyway the latest will also crash due to some refactors made (I didn't realise this would cause issues with DT BOP), I've opened the-realest-stu/DynamicTrees-BOP#68 to fix this.

**Comment by Mr-Syntax** [comment]
ahh okay thanks for being so fast and responsive bro :)
