### ISSUE TITLE
NPE at addHitEffects when Dynamic Tree log is broken

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#61]
Seems to happen at random.

**Expected Outcome:** 

- Tree dies and drops seeds, etc.

**Actual Outcome:** 

- 50% of the time it crashes client with NPE.

_________________________________________________________

[03:26:18] [Thread-20/WARN] [THAUMCRAFT]: No auras found!
[03:26:18] [Thread-20/INFO] [THAUMCRAFT]: Stopping aura thread for dim 0
[03:26:18] [Server thread/INFO] [FML]: Unloading dimension 0
[03:26:20] [Server thread/INFO] [FML]: Applying holder lookups
[03:26:20] [Server thread/INFO] [FML]: Holder lookups applied
[03:26:22] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.addHitEffects(BlockRooty.java:440) ~[BlockRooty.class:?]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at Reflector.callBoolean(Reflector.java:828) ~[Reflector.class:?]
	at net.minecraft.client.particle.ParticleManager.addBlockHitEffects(ParticleManager.java:570) ~[btg.class:?]
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1480) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[03:26:23] [Thread-29/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §6startup.outdatedversiondev
[03:26:23] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OTGCorePlugin (OTG-Core.jar)
  FarseekCoreMod (Farseek-1.12-2.2.5.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 4/26/18 3:26 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.addHitEffects(BlockRooty.java:440)
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:828)
	at net.minecraft.client.particle.ParticleManager.addBlockHitEffects(ParticleManager.java:570)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1480)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.addHitEffects(BlockRooty.java:440)
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:828)
	at net.minecraft.client.particle.ParticleManager.addBlockHitEffects(ParticleManager.java:570)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1480)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ShamanProgrammer'/249, l='MpServer', x=-1442.96, y=68.00, z=3207.19]]
	Chunk stats: MultiplayerChunkCache: 286, 286
	Level seed: 0
	Level generator: ID 06 - OTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-923,64,2543), Chunk: (at 5,4,15 in -58,158; contains blocks -928,0,2528 to -913,255,2543), Region: (-2,4; contains chunks -64,128 to -33,159, blocks -1024,0,2048 to -513,255,2559)
	Level time: 45070 game time, 54432 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntitySkeleton['Skeleton'/256, l='MpServer', x=-1431.50, y=29.00, z=3236.50], EntityFishCod['Cod'/257, l='MpServer', x=-1453.01, y=64.00, z=3231.67], EntityFishCod['Cod'/1, l='MpServer', x=-1395.90, y=63.00, z=3224.90], EntityFishCod['Cod'/769, l='MpServer', x=-1405.11, y=63.82, z=3133.78], EntityFishCod['Cod'/2, l='MpServer', x=-1422.69, y=63.00, z=3230.20], EntityFishCod['Cod'/770, l='MpServer', x=-1408.47, y=62.20, z=3132.73], EntityFishCod['Cod'/3, l='MpServer', x=-1420.87, y=64.14, z=3227.39], EntityFishCod['Cod'/4, l='MpServer', x=-1421.61, y=63.00, z=3229.84], EntityItem['item.item.oakseed'/260, l='MpServer', x=-1457.88, y=64.00, z=3268.53], EntityFishCod['Cod'/261, l='MpServer', x=-1405.87, y=64.20, z=3132.75], EntityFishCod['Cod'/263, l='MpServer', x=-1416.69, y=64.00, z=3146.31], EntityFishCod['Cod'/265, l='MpServer', x=-1375.84, y=64.19, z=3173.92], EntityButterfly['Butterfly'/778, l='MpServer', x=-1453.89, y=77.14, z=3162.20], EntityZombie['Zombie'/11, l='MpServer', x=-1440.30, y=17.00, z=3196.50], EntityFishCod['Cod'/267, l='MpServer', x=-1380.80, y=63.00, z=3158.74], EntityButterfly['Butterfly'/779, l='MpServer', x=-1465.32, y=70.73, z=3173.44], EntityFishCod['Cod'/268, l='MpServer', x=-1373.33, y=64.05, z=3169.31], Estia Sophronia/3599091642657841342/-1407/61/3225/WorldClient, EntityFishCod['Cod'/269, l='MpServer', x=-1461.66, y=64.09, z=3234.10], Ilias Sophronia/8808152435173758728/-1409/67/3259/WorldClient, EntityCreeper['Creeper'/271, l='MpServer', x=-1486.50, y=38.00, z=3268.50], EntityCreeper['Creeper'/272, l='MpServer', x=-1487.50, y=38.00, z=3266.50], EntityPlayerSP['ShamanProgrammer'/249, l='MpServer', x=-1442.96, y=68.00, z=3207.19], EntityButterfly['Butterfly'/277, l='MpServer', x=-1494.36, y=68.17, z=3277.70], EntityCreeper['Creeper'/790, l='MpServer', x=-1441.50, y=19.00, z=3261.50], EntityButterfly['Butterfly'/279, l='MpServer', x=-1497.00, y=73.50, z=3255.10], EntityCreeper['Creeper'/792, l='MpServer', x=-1401.50, y=13.00, z=3167.50], EntityZombie['Zombie'/281, l='MpServer', x=-1428.84, y=21.00, z=3183.50], EntityHenLeghorn['Leghorn Hen'/282, l='MpServer', x=-1425.32, y=73.00, z=3164.54], EntityItem['item.item.oakseed'/284, l='MpServer', x=-1465.14, y=69.00, z=3201.69], EntityBat['Bat'/286, l='MpServer', x=-1493.26, y=20.99, z=3256.45], EntityZombie['Zombie'/287, l='MpServer', x=-1500.50, y=36.00, z=3238.50], Helena Sophronia/5626954758174708885/-1408/68/3259/WorldClient, Leo Sophronia/3491575239310844805/-1410/67/3258/WorldClient, Iassonas Xenos/7547506995109267952/-1419/59/3226/WorldClient, EntityBat['Bat'/446, l='MpServer', x=-1498.89, y=17.06, z=3256.69], EntityEnderman['Enderman'/454, l='MpServer', x=-1445.50, y=35.00, z=3180.50], EntityItem['item.tile.oreIron'/455, l='MpServer', x=-1442.13, y=59.00, z=3177.88], EntityZombie['Zombie'/456, l='MpServer', x=-1515.78, y=21.00, z=3266.50], EntityButterfly['Butterfly'/461, l='MpServer', x=-1447.03, y=83.71, z=3166.35], Hestia Xenos/2796143176630865529/-1420/59/3225/WorldClient, EntityButterfly['Butterfly'/595, l='MpServer', x=-1395.74, y=70.20, z=3266.28], EntitySkeleton['Skeleton'/470, l='MpServer', x=-1450.51, y=31.00, z=3137.30], Iljios Sophronia/4820887479700349693/-1425/62/3229/WorldClient, Estia Sophronia/381418202083749574/-1409/68/3260/WorldClient, EntityMinecartChest['Minecart with Chest'/477, l='MpServer', x=-1483.50, y=26.06, z=3155.50], EntityFishCod['Cod'/605, l='MpServer', x=-1382.19, y=65.00, z=3283.39], EntitySkeleton['Skeleton'/740, l='MpServer', x=-1432.50, y=19.00, z=3185.50], EntityZombie['Zombie'/741, l='MpServer', x=-1426.43, y=13.00, z=3260.75], EntityCreeper['Creeper'/742, l='MpServer', x=-1475.50, y=26.00, z=3154.50], EntityBrainyZombie['Angry Zombie'/743, l='MpServer', x=-1476.50, y=26.00, z=3155.50], EntityBrainyZombie['Angry Zombie'/744, l='MpServer', x=-1471.50, y=26.00, z=3155.50], EntityItem['item.item.oakseed'/620, l='MpServer', x=-1393.44, y=71.00, z=3201.28], EntitySkeleton['Skeleton'/492, l='MpServer', x=-1439.73, y=27.00, z=3130.50], EntitySkeleton['Skeleton'/493, l='MpServer', x=-1447.50, y=31.00, z=3130.50], EntityBat['Bat'/622, l='MpServer', x=-1430.61, y=19.05, z=3265.15], EntityFishCod['Cod'/756, l='MpServer', x=-1404.20, y=64.00, z=3227.89], Demostenes Helios/2527853812228430726/-1404/68/3265/WorldClient, Platon Sophronia/4171010218124231979/-1440/67/3189/WorldClient, Sokrates Ligeia/5770638796065864941/-1410/67/3259/WorldClient, EntityItem['item.item.oakseed'/251, l='MpServer', x=-1447.79, y=69.00, z=3205.34], EntityZombie['Zombie'/508, l='MpServer', x=-1458.50, y=34.00, z=3132.50], EntityItem['item.item.oakseed'/253, l='MpServer', x=-1450.30, y=68.00, z=3209.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by ghost** [comment]
I remember something like this happening before.  I think it had something to do with the block position forge is reporting is not the real location of the blockstate. Makes it seem like it's random but it actually has something to do with where on the block you are hitting or falling.  If it's too close to another block then forge goofs on the math.  I believe it's a forge bug but I'll put in checks to prevent the crash anyway.

**Comment by ghost** [comment]
Fixed in dev
