### ISSUE TITLE
Rare game crash on patchouli book generation

### ISSUE THREAD

**Issue by Chaos02** [ferreusveritas/Dynamic-Trees#713]
**Description**
Crash to desktop after freeze, no report, log suddenly ends a couple messages after this:
```
[Render thread/ERROR] [patchouli/]: Error loading book dynamictrees:guide, using empty contents and ignoring extensions
com.google.gson.JsonSyntaxException: Expected sortnum to be a Int, was "1"
	at net.minecraft.util.GsonHelper.m_13897_(GsonHelper.java:254) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.util.GsonHelper.m_13824_(GsonHelper.java:268) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at vazkii.patchouli.client.book.BookCategory.<init>(BookCategory.java:56) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.loadCategory(BookContentsBuilder.java:150) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.load(BookContentsBuilder.java:127) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.loadFrom(BookContentsBuilder.java:78) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:210) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.18.2-71.1.jar%23297!/:1.18.2-71.1]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$clk000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1135) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1014) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23386!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**To Reproduce**
No known steps - load world, move around seems to be it...

**Additional context**

**Crashes**
No crash report generated!!

**Mods List**
[Mod List](https://hastebin.com/ujurifanah.rb)

**Versions**
- [DynamicTrees-1.18.2-0.11.0-Alpha2.jar](https://www.curseforge.com/minecraft/mc-mods/dynamictrees/files/3831578)
- [Forge 1.18.2-40.1.73.jar](https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.1.73/forge-1.18.2-40.1.73-installer.jar)
- Java 17 (through Curseforge client)
- Windows 11 Insider Preview 22H2 (22622.450)

**Comment by Chaos02** [comment]
Hey I've found that it probably isn't the patchouli book generation (maybe that aswell) but I believe that this has caused my latest crash:
```
[Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkMap.m_203056_(ChunkMap.java:602) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at com.ferreusveritas.dynamictrees.systems.poissondisc.PoissonDiscHelper.solveDiscs(PoissonDiscHelper.java:208) ~[DynamicTrees-1.18.2-0.11.0-Alpha2.jar%23177!/:1.18.2-0.11.0-Alpha2]
	at com.ferreusveritas.dynamictrees.systems.poissondisc.LevelPoissonDiscProvider.generatePoissonDiscs(LevelPoissonDiscProvider.java:213) ~[DynamicTrees-1.18.2-0.11.0-Alpha2.jar%23177!/:1.18.2-0.11.0-Alpha2]
	at com.ferreusveritas.dynamictrees.systems.poissondisc.LevelPoissonDiscProvider.getPoissonDiscs(LevelPoissonDiscProvider.java:55) ~[DynamicTrees-1.18.2-0.11.0-Alpha2.jar%23177!/:1.18.2-0.11.0-Alpha2]
	at com.ferreusveritas.dynamictrees.systems.poissondisc.UniversalPoissonDiscProvider.getPoissonDiscs(UniversalPoissonDiscProvider.java:36) ~[DynamicTrees-1.18.2-0.11.0-Alpha2.jar%23177!/:1.18.2-0.11.0-Alpha2]
	at com.ferreusveritas.dynamictrees.worldgen.DynamicTreeFeature.m_142674_(DynamicTreeFeature.java:47) ~[DynamicTrees-1.18.2-0.11.0-Alpha2.jar%23177!/:1.18.2-0.11.0-Alpha2]
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Chaos02** [comment]
Answer from patchouli:
https://github.com/VazkiiMods/Patchouli/issues/601#issuecomment-1214416412

**Comment by Chaos02** [comment]
Hey, just checking in - I'm still getting frequent crashes because of the Poissondisk helper
(`at com.ferreusveritas.dynamictrees.systems.poissondisc.PoissonDiscHelper.solveDiscs(PoissonDiscHelper.java:208)`)
