### ISSUE TITLE
Server crashes when I go into a certain area

### ISSUE THREAD

**Issue by E-daw** [ferreusveritas/Dynamic-Trees#82]
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.ferreusveritas.dynamictrees.api.TreeHelper.ageVolume(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;III)V
	at dynamictreesbop.trees.TreePalm$SpeciesPalm.postGrow(TreePalm.java:153) ~[TreePalm$SpeciesPalm.class:?]
	at com.ferreusveritas.dynamictrees.trees.Species.grow(Species.java:679) ~[Species.class:?]
	at com.ferreusveritas.dynamictrees.trees.Species.update(Species.java:560) ~[Species.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.updateTree(BlockRooty.java:168) ~[BlockRooty.class:?]
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.func_180645_a(BlockRooty.java:140) ~[BlockRooty.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]

**Comment by E-daw** [comment]
I updated it and ended up fixing it, nvm
