### ISSUE TITLE
Serene Seasons and Dynamic Trees

### ISSUE THREAD

**Issue by osmanyzero** [ferreusveritas/Dynamic-Trees#962]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-10-25 14:17:13
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: sereneseasons/config/ServerConfig
	at com.ferreusveritas.dynamictrees.compat.season.SereneSeasonsSeasonProvider.lambda$registerSereneSeasonsProvider$0(SereneSeasonsSeasonProvider.java:44) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at com.ferreusveritas.dynamictrees.compat.season.NormalSeasonManager.createProvider(NormalSeasonManager.java:32) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at com.ferreusveritas.dynamictrees.compat.season.NormalSeasonManager.lambda$getContext$1(NormalSeasonManager.java:37) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at com.ferreusveritas.dynamictrees.compat.season.NormalSeasonManager.getContext(NormalSeasonManager.java:36) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at com.ferreusveritas.dynamictrees.compat.season.NormalSeasonManager.updateTick(NormalSeasonManager.java:73) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at com.ferreusveritas.dynamictrees.compat.season.SeasonHelper.updateTick(SeasonHelper.java:43) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading}
	at com.ferreusveritas.dynamictrees.event.handler.CommonEventHandler.onWorldTick(CommonEventHandler.java:24) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading,pl:runtimedistcleaner:A}
	at com.ferreusveritas.dynamictrees.event.handler.__CommonEventHandler_onWorldTick_LevelTickEvent.invoke(.dynamic) ~[DynamicTrees-1.20.1-1.3.3.jar%23426!/:1.20.1-1.3.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:954) ~[forge-1.20.1-47.3.11-universal.jar%23545!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1163) ~[server-1.20.1-20230612.114412-srg.jar%23540!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23540!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071) ~[server-1.20.1-20230612.114412-srg.jar%23540!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23540!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23540!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:842) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
Caused by: java.lang.ClassNotFoundException: sereneseasons.config.ServerConfig
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	... 19 more

**Comment by BL4CKLOTU5www** [comment]
Fixed in the lastest version(1.3.4)
